default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>

development:
  <<: *default
  database: minesweeper_development

test:
  <<: *default
  database: minesweeper_test

production:
  <<: *default
  database: minesweeper_production
